name: Deploy Laravel Project on push muhib
on:
  push:
    branches:
      - ProductAttribute
jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Configure PHP 8.1
        uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
        with:
          php-version: '8.1'
      - name: Get the latest code
        uses: actions/checkout@v2.3.2
      - uses: actions/setup-node@master
      - name: Install Dependencies
        run: composer install --no-dev --no-interaction --prefer-dist
      - name: Install Dependencies for vue
        run: npm install
      - name: Directory Permissions
        run: php artisan key:generate
        run: php artisan config:cache
        run: php artisan route:cache
        run: php artisan view:cache
      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ${{ secrets.SERVER }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          server-dir: "/htdocs/"

